# Use OpenJDK as base image
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the Maven wrapper and pom.xml files
COPY .mvn/ .mvn
COPY mvnw .
COPY mvnw.cmd .
COPY pom.xml .

# Make the Maven wrapper executable
RUN chmod +x mvnw

# Download dependencies
RUN ./mvnw dependency:go-offline

# Copy the entire source code
COPY src ./src

# Package the app
RUN ./mvnw clean package -DskipTests

# Run the JAR file
CMD ["java", "-jar", "target/backend-0.0.1-SNAPSHOT.jar"]
